# KNN

Prompt: 
```
Oi, pode implementar o algoritmo KNN, na linguagem python, porém sem usar bibliotecas com o algoritmo já pronto, apenas bibliotecas vetoriais como o numpy.
```    
Resposta:
```python
Claro! Aqui está uma implementação simples do algoritmo K-Nearest Neighbors (KNN) em Python utilizando apenas bibliotecas básicas como o NumPy para manipulação de arrays:

python
Copy code
import numpy as np
from collections import Counter

class KNN:
    def __init__(self, k=3):
        self.k = k
    
    def fit(self, X_train, y_train):
        """Armazena os dados de treino."""
        self.X_train = X_train
        self.y_train = y_train
    
    def predict(self, X_test):
        """Prediz os rótulos de dados de teste."""
        predictions = [self._predict(x) for x in X_test]
        return np.array(predictions)
    
    def _predict(self, x):
        """Prediz o rótulo para um único ponto de dados."""
        # Calcula as distâncias euclidianas de x para todos os pontos de treino
        distances = [np.linalg.norm(x - x_train) for x_train in self.X_train]
        
        # Pega os índices das k menores distâncias
        k_indices = np.argsort(distances)[:self.k]
        
        # Pega os rótulos correspondentes a esses k pontos mais próximos
        k_nearest_labels = [self.y_train[i] for i in k_indices]
        
        # Retorna o rótulo mais comum (maioria)
        most_common = Counter(k_nearest_labels).most_common(1)
        return most_common[0][0]

# Exemplo de uso:
if __name__ == "__main__":
    # Dados de treino (X_train -> características, y_train -> rótulos)
    X_train = np.array([[1, 2], [2, 3], [3, 4], [6, 5], [7, 7], [8, 9]])
    y_train = np.array([0, 0, 0, 1, 1, 1])
    
    # Dados de teste
    X_test = np.array([[5, 5], [0, 1]])

    # Instanciando o classificador KNN com k=3
    knn = KNN(k=3)
    
    # Treinando o modelo
    knn.fit(X_train, y_train)
    
    # Fazendo previsões
    predictions = knn.predict(X_test)
    print("Predições:", predictions)
Explicação:
KNN é um algoritmo baseado em instância que armazena todos os dados de treino e, ao prever um novo ponto de dados, ele:
Calcula a distância (nesse caso, distância euclidiana) do ponto de teste para todos os pontos de treino.
Seleciona os k vizinhos mais próximos (menores distâncias).
Faz uma votação majoritária dos rótulos desses vizinhos para determinar a classe de saída.
Exemplo de saída:
Se executarmos o exemplo acima, as predições podem ser algo como:

less
Copy code
Predições: [1 0]
Esse algoritmo é bastante simples e pode ser ajustado para incluir variações, como diferentes métricas de distância ou técnicas de ponderação para os vizinhos.
```

In [5]:
import numpy as np
from collections import Counter

class KNN:
    def __init__(self, k=3):
        self.k = k

    def fit(self, X_train, y_train):
        self.X_train = X_train
        self.y_train = y_train

    def predict(self, X_test):
        predictions = [self._predict(x) for x in X_test]
        return np.array(predictions)

    def _predict(self, x):
        distances = [np.linalg.norm(x - x_train) for x_train in self.X_train]
        k_indices = np.argsort(distances)[:self.k]
        k_nearest_labels = [self.y_train[i] for i in k_indices]
        most_common = Counter(k_nearest_labels).most_common(1)
        return most_common[0][0]


## Testando o KNN

In [10]:
from KNN import KNN
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score


if __name__ == "__main__":
    iris = datasets.load_iris()
    X, y = iris.data, iris.target
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

    scaler = StandardScaler()
    X_train = scaler.fit_transform(X_train)
    X_test = scaler.transform(X_test)

    knn = KNN(k=3)
    knn.fit(X_train, y_train)

    predictions = knn.predict(X_test)

    accuracy = accuracy_score(y_test, predictions)
    precision = precision_score(y_test, predictions, average='macro')
    recall = recall_score(y_test, predictions, average='macro')
    f1 = f1_score(y_test, predictions, average='macro')

    conf_matrix = confusion_matrix(y_test, predictions)

    print(f"Acurácia: {accuracy * 100:.2f}%")
    print(f"Precisão: {precision * 100:.2f}%")
    print(f"Recall: {recall * 100:.2f}%")
    print(f"F1-Score: {f1 * 100:.2f}%")
    print("Matriz de Confusão:")
    print(conf_matrix)


Acurácia: 96.67%
Precisão: 96.67%
Recall: 96.97%
F1-Score: 96.66%
Matriz de Confusão:
[[10  0  0]
 [ 0  9  0]
 [ 0  1 10]]


# Naive Bayes

In [ ]:
print('hi')